sylius_ui:
    events:
        sylius.shop.product.show.add_to_cart_form:
            blocks:
                setono_gift_card_information:
                    template: "@SetonoSyliusGiftCardPlugin/shop/product/show/_gift_card_information.html.twig"
                    priority: 10

        sylius.shop.cart.summary:
            blocks:
                setono_gift_cards:
                    template: "@SetonoSyliusGiftCardPlugin/shop/cart/_gift_cards.html.twig"
                    priority: 10

        sylius.shop.cart.summary.totals:
            blocks:
                setono_gift_card_totals:
                    template: "@SetonoSyliusGiftCardPlugin/shop/cart/_gift_card_totals.html.twig"
                    priority: 10
