winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                setono_sylius_gift_card__reconcile_gift_cards:
                    on: ["complete"]
                    do: ["@setono_sylius_gift_card.operator.order_gift_card", "reconcile"]
                    args: ["object"]

    sylius_order_payment:
        callbacks:
            after:
                setono_sylius_gift_card__enable_gift_cards:
                    on: ["pay"]
                    do: ["@setono_sylius_gift_card.operator.order_gift_card", "enable"]
                    args: ["object"]
                setono_sylius_gift_card__send_gift_cards:
                    on: ["pay"]
                    do: ["@setono_sylius_gift_card.operator.order_gift_card", "send"]
                    args: ["object"]

    sylius_order:
        callbacks:
            after:
                setono_sylius_gift_card__commit_redemption:
                    on: ["create"]
                    do: ["@setono_sylius_gift_card.redemption_method", "commit"]
                    args: ["object"]
                setono_sylius_gift_card__rollback_redemption:
                    on: ["cancel"]
                    do: ["@setono_sylius_gift_card.redemption_method", "rollback"]
                    args: ["object"]
                setono_sylius_gift_card__disable_gift_cards:
                    on: ["cancel"]
                    do: ["@setono_sylius_gift_card.operator.order_gift_card", "disable"]
                    args: ["object"]
