services:
    php:
        image: ghcr.io/sylius/sylius-php:8.4-alpine
    mysql:
        image: mysql:8.4
        platform: linux/amd64
        healthcheck:
            test: '/usr/bin/mysql --execute "SHOW databases;"'
            timeout: 3s
            interval: 1s
            retries: 10
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        cap_add:
            - SYS_NICE # prevent "mbind: Operation not permitted" errors
        ports:
            - ${MYSQL_PORT:-33062}:3306
        volumes:
            - setono-sylius-gift-card-plugin-mysql-data:/var/lib/mysql:rw
    nginx:
        image: ghcr.io/sylius/sylius-nginx:latest
        depends_on:
            -   php
    chrome:
        image: chromedp/headless-shell:stable
        command: --remote-allow-origins=*

    chrome-proxy:
        image: nginx:alpine
        volumes:
            - ./docker/nginx/chrome-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - chrome

    mailhog:
        # do not use in production!
        image: axllent/mailpit:latest

volumes:
    setono-sylius-gift-card-plugin-mysql-data:
