setono_sylius_gift_card_admin_gift_card:
    resource: |
        alias: setono_sylius_gift_card.gift_card
        section: admin
        permission: true
        only: [index, create, update, delete, bulkDelete]
        templates: '@SyliusAdmin\\Crud'
        redirect: index
        grid: setono_sylius_gift_card_admin_gift_card
        vars:
            all:
                subheader: setono_sylius_gift_card.ui.manage_gift_cards
                templates:
                    form: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/_form.html.twig"
            index:
                icon: 'gift'
    type: sylius.resource

setono_sylius_gift_card_admin_gift_card_balance:
    path: /gift-cards/balance
    methods: [GET]
    defaults:
        _controller: setono_sylius_gift_card.controller.action.admin.balance
        _sylius:
            section: admin
            permission: true

setono_sylius_gift_card_admin_create_gift_card_product:
    path: /gift-cards/create-product
    methods: [GET, POST]
    defaults:
        _controller: setono_sylius_gift_card.controller.action.admin.create_gift_card_product
        _sylius:
            section: admin
            permission: true

setono_sylius_gift_card_admin_gift_card_pdf:
    path: /gift-cards/{id}/pdf
    methods: [GET]
    requirements:
        id: \d+
    defaults:
        _controller: setono_sylius_gift_card.controller.action.download_pdf
        _sylius:
            section: admin
            permission: true

setono_sylius_gift_card_admin_gift_card_adjust_balance:
    path: /gift-cards/{id}/adjust-balance
    methods: [GET, POST]
    requirements:
        id: \d+
    defaults:
        _controller: setono_sylius_gift_card.controller.action.admin.adjust_balance
        _sylius:
            section: admin
            permission: true

setono_sylius_gift_card_admin_gift_card_design:
    resource: |
        alias: setono_sylius_gift_card.gift_card_design
        section: admin
        permission: true
        templates: '@SyliusAdmin\\Crud'
        redirect: index
        grid: setono_sylius_gift_card_admin_gift_card_design
        vars:
            all:
                subheader: setono_sylius_gift_card.ui.manage_gift_card_designs
                templates:
                    form: "@SetonoSyliusGiftCardPlugin/Admin/GiftCardDesign/_form.html.twig"
            index:
                icon: 'palette'
    type: sylius.resource

setono_sylius_gift_card_admin_gift_card_design_preview_pdf:
    path: /gift-card-designs/{id}/preview-pdf
    methods: [GET]
    requirements:
        id: \d+
    defaults:
        _controller: setono_sylius_gift_card.controller.action.admin.preview_design_pdf
        _sylius:
            section: admin
            permission: true
