setono_sylius_gift_card_admin_gift_card:
    resource: |
        alias: setono_sylius_gift_card.gift_card
        section: admin
        permission: true
        only: [index, update, delete, bulkDelete]
        templates: '@SyliusAdmin\\Crud'
        redirect: index
        grid: setono_sylius_gift_card_admin_gift_card
        vars:
            all:
                subheader: setono_sylius_gift_card.ui.manage_gift_cards
                templates:
                    form: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/_form.html.twig"
            index:
                icon: 'gift'
    type: sylius.resource

setono_sylius_gift_card_admin_gift_card_design:
    resource: |
        alias: setono_sylius_gift_card.gift_card_design
        section: admin
        permission: true
        templates: '@SyliusAdmin\\Crud'
        redirect: index
        grid: setono_sylius_gift_card_admin_gift_card_design
        vars:
            all:
                subheader: setono_sylius_gift_card.ui.manage_gift_card_designs
                templates:
                    form: "@SetonoSyliusGiftCardPlugin/Admin/GiftCardDesign/_form.html.twig"
            index:
                icon: 'palette'
    type: sylius.resource
