setono_sylius_gift_card_admin_ajax_generate_pdf:
    path: /gift-card-configurations/{id}/generate-encoded-example-pdf
    methods: [ PUT ]
    controller: setono_sylius_gift_card.controller.action.generate_encoded_example_pdf
    requirements:
        id: \d+
