sylius_twig_hooks:
    hooks:
        'sylius_shop.product.show.content.info.summary.add_to_cart':
            setono_sylius_gift_card_information:
                template: '@SetonoSyliusGiftCardPlugin/Shop/Product/Show/_addToCartGiftCardInformation.html.twig'
                priority: 50

        'sylius_shop.cart.index.content.form.sections.general.summary':
            setono_sylius_gift_card_applied_gift_cards:
                template: '@SetonoSyliusGiftCardPlugin/Shop/Cart/Summary/_appliedGiftCards.html.twig'
                priority: 150

        'sylius_shop.cart.index.content':
            setono_sylius_gift_card_add_gift_card_to_order:
                template: '@SetonoSyliusGiftCardPlugin/Shop/Cart/Summary/_addGiftCardToOrder.html.twig'
                priority: 50

        'sylius_admin.order.show.content.sections.summary':
            setono_sylius_gift_card_total:
                template: '@SetonoSyliusGiftCardPlugin/Admin/Order/Show/Summary/_giftCardTotal.html.twig'
                priority: 50

        'sylius_shop.shared.order.show.summary.table_summary':
            setono_sylius_gift_card_total:
                template: '@SetonoSyliusGiftCardPlugin/Shop/Order/Show/Summary/_giftCardTotal.html.twig'
                priority: 250
