imports:
    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/grids.yaml" }
    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/sylius_ui.yaml" }

    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order.yaml" }
    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order_checkout.yaml" }
    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order_payment.yaml" }

sylius_mailer:
    emails:
        gift_card_customer:
            subject: setono_sylius_gift_card.email.new_gift_card
            template: "@SetonoSyliusGiftCardPlugin/Email/giftCardToCustomer.html.twig"
        gift_card_order:
            subject: setono_sylius_gift_card.email.your_gift_cards_you_bought_in_the_order
            template: "@SetonoSyliusGiftCardPlugin/Email/giftCardsFromOrder.html.twig"

framework:
    serializer:
        enabled: true
        mapping:
            paths:
                - '%kernel.project_dir%/vendor/setono/sylius-gift-card-plugin/src/Resources/config/serialization/'

liip_imagine:
    filter_sets:
        setono_sylius_gift_card_background:
            filters:
                thumbnail: { size: [1200], mode: inset }

